version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: trading_console_db
    environment:
      POSTGRES_DB: trading_console
      POSTGRES_USER: trading_user
      POSTGRES_PASSWORD: trading_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Redis for Celery
  redis:
    image: redis:7-alpine
    container_name: trading_console_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: trading_console_backend
    environment:
      - DATABASE_URL=postgresql://trading_user:trading_password@postgres:5432/trading_console
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-very-secret-key-change-in-production
      - ENVIRONMENT=development
      # 代理配置（用于访问海外交易所API）
      - USE_PROXY=${USE_PROXY:-false}
      - PROXY_HOST=${PROXY_HOST:-host.docker.internal}
      - PROXY_PORT=${PROXY_PORT:-1080}
      - PROXY_TYPE=${PROXY_TYPE:-socks5}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    restart: unless-stopped
    # 允许容器访问宿主机网络（用于代理）
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: trading_console_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  postgres_data:
